name: Run Tests

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # jeśli potrzebujesz

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings --cov=.

      - name: Upload coverage report
        uses: uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
